### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by FilipeCuco** [JvstDev/grm-discord#1]
hi, i tried to do that but it keeps sending me a player.%s does not have a discord account linked!

![image](https://github.com/JvstDev/grm-discord/assets/116587926/7eb03a9f-736c-4639-8f05-75b8c9a8fce2)
![image](https://github.com/JvstDev/grm-discord/assets/116587926/cdf3343a-a3c7-4aaf-9991-9afa384047ff)

**Comment by JvstDev** [comment]
Yo! you must enter the player id (source) instead of the discord ID.
Attention! the SetNickname will not work if you are the owner of the server.

```lua
RegisterComand("testc", function(source, args, raw)
     exports['grm-discord']:SetNickname(source, "Test")
end) 
```

Join in my discord for support: https://discord.gg/grmdev
